In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [28]:
clf1 = LogisticRegression(max_iter=1000)
clf2 = DecisionTreeClassifier()

In [29]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [30]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8852459016393442
Accuracy of Decision Trees 0.819672131147541


In [32]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  26   6
1   1  28

In [33]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0   1
0  23   9
1   2  27

In [34]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [13]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
267             0                               0                         1
288             0                               0                         0
53              1                               1                         1
159             1                               1                         1
169             0                               0                         0
231             0                               0                         0
192             0                               0                         0
178             0                               0                         0
112             1                               1                         1
13              1                               1                         1

In [35]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [36]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   1  28
--------------------------------------------------
Precision -  0.8235294117647058
Recall -  0.9655172413793104
F1 score -  0.888888888888889


In [37]:
print("For Decision Tree Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decision Tree Model
--------------------------------------------------
    0   1
0  23   9
1   2  27
--------------------------------------------------
Precision -  0.75
Recall -  0.9310344827586207
F1 score -  0.8307692307692308


In [38]:
precision_score(y_test,y_pred1,average=None)

array([0.96296296, 0.82352941])

In [39]:
precision_score(y_test,y_pred2,average=None)

array([0.92, 0.75])

In [40]:
recall_score(y_test,y_pred2,average=None)

array([0.71875   , 0.93103448])