In [35]:
import numpy as np
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[5]

5

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[:5]

array([0, 1, 2, 3, 4])

In [39]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[5:9]

array([5, 6, 7, 8])

### Broadcast Example

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
sliced = arr[0:5]
sliced

array([0, 1, 2, 3, 4])

In [45]:
sliced[:] = 0

In [46]:
sliced

array([0, 0, 0, 0, 0])

In [47]:
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [48]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [49]:
arr_copy[0:5] = 45
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy

array([45, 45, 45, 45, 45,  5,  6,  7,  8,  9, 10])

In [51]:
arr_copy[::2]

array([45, 45, 45,  6,  8, 10])

In [52]:
arr_2d = np.array([[4, 5, 6], [8, 7, 8], [5, 4, 8]])
arr_2d

array([[4, 5, 6],
       [8, 7, 8],
       [5, 4, 8]])

In [53]:
arr_2d[:2, 1:]

array([[5, 6],
       [7, 8]])

### Conditional Selection

In [54]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [55]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2,
                      1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])


total_rolls_over_two = dice_rolls[dice_rolls > 2]

total_rolls_over_two

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [56]:
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [57]:
print(arr)

[ 0  0  0  0  0  5  6  7  8  9 10]


In [58]:
arr = 0
arr

0

type(arr)

In [59]:
type(arr)

int

In [60]:
arr = np.linspace(0, 16, 15, dtype=int)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16])