In [6]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[5]

5

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[5:9]

array([5, 6, 7, 8])

### Broadcast Example

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[0:5]=100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange (0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
sliced=arr[0:5]

In [20]:
sliced

array([0, 1, 2, 3, 4])

In [21]:
sliced

array([0, 1, 2, 3, 4])

In [22]:
sliced[:]=0

In [23]:
sliced

array([0, 0, 0, 0, 0])

In [24]:
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [25]:
 arr_copy=arr.copy()

In [26]:
arr_copy

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [27]:
arr_copy[0:5]=45

In [28]:
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [29]:
arr_copy

array([45, 45, 45, 45, 45,  5,  6,  7,  8,  9, 10])

In [30]:
arr_copy[::2]

array([45, 45, 45,  6,  8, 10])

In [31]:
arr_2d = np.array([[4,5,6],[8,7,8],[5,4,8]])
arr_2d

array([[4, 5, 6],
       [8, 7, 8],
       [5, 4, 8]])

In [32]:
arr_2d[:2,1:]

array([[5, 6],
       [7, 8]])

### Conditional Selection

In [33]:
arr > 4 

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [34]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls[dice_rolls>2]
total_rolls_over_two

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [35]:
arr

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [36]:
print(arr)

[ 0  0  0  0  0  5  6  7  8  9 10]


In [37]:
arr = 0

In [38]:
arr

0

type(arr)

In [39]:
type(arr)

int

In [44]:
arr = np.linspace(0,16,15,dtype =int)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16])