In [44]:
import numpy as np

# Create a 1D numpy array with values from 0 to 9
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# Add 5 to each element in the array
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr = arr+5

In [48]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
# 4/0 

In [50]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr/0

C:\Users\piyus\AppData\Local\Temp\ipykernel_31224\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [55]:
arr= np.arange(0,10)

In [56]:
arr/0

C:\Users\piyus\AppData\Local\Temp\ipykernel_31224\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
C:\Users\piyus\AppData\Local\Temp\ipykernel_31224\4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [57]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
1/arr

C:\Users\piyus\AppData\Local\Temp\ipykernel_31224\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [59]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [62]:
np.log(arr)

C:\Users\piyus\AppData\Local\Temp\ipykernel_31224\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [63]:
arr2d = np.arange(20).reshape(4, 5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Sure, I can help with that. Please provide the content of the notebook cells that you want to add comments to.

In [64]:
arr2d.sum(axis=0) # vertical Sum of Rows (0+5+10+15+20)

array([30, 34, 38, 42, 46])

In [65]:
arr2d.sum(axis=1) # Horizontal Sum of Columns(0+1+2+3+4)

array([10, 35, 60, 85])