In [33]:
import numpy as np

mylist = [1, 1, 25, 65]
arr = np.array(mylist)

In [34]:
print(type(mylist))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [35]:
myMatrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

myNpMtrx = np.array(myMatrix)
myNpMtrx

In [37]:
type(myNpMtrx)

numpy.ndarray

In [38]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [39]:
myNpMtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [41]:
np.zeros((5, 8), int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
np.linspace(0, 10, 17, dtype=int)

array([ 0,  0,  1,  1,  2,  3,  3,  4,  5,  5,  6,  6,  7,  8,  8,  9, 10])

In [43]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [44]:
np.random.rand(5, 2)

array([[0.91464056, 0.48087397],
       [0.71967711, 0.36536724],
       [0.05723759, 0.21868496],
       [0.3168903 , 0.9256706 ],
       [0.60852417, 0.81385571]])

In [45]:
np.random.randn(10)

array([-0.55692439,  0.68594028,  1.94471766,  1.01648946,  0.79274606,
        0.10341219, -0.73705051,  0.50921032, -0.44918952,  1.33799264])

In [46]:
np.random.randint(0, 101, size=10)

array([95, 63, 98, 22, 27, 32, 16, 75, 58, 60])

In [47]:
np.random.rand(4)
np.random.seed(45)

In [48]:
arr = np.arange(1, 25)
arr

In [50]:
arr.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
myarr = np.random.randint(2, 12, size=4)

In [52]:
myarr

array([5, 2, 7, 5])

In [53]:
print(myarr)

[5 2 7 5]


In [54]:
myarr.argmax()

2

In [55]:
myarr.shape

(4,)

In [56]:
myarr.reshape(4, 1)

array([[5],
       [2],
       [7],
       [5]])

In [57]:
myarr

array([5, 2, 7, 5])

In [58]:
myarr = myarr.reshape(4, 1)

In [59]:
myarr

array([[5],
       [2],
       [7],
       [5]])

In [60]:
myarr.shape  # returns current shape of the array

(4, 1)