In [1]:
import numpy as np

In [2]:
mylist = [1,1,25,65]

In [3]:
arr = np.array(mylist)

In [4]:
print(type(mylist))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [31]:
myNpMtrx = np.array(myMatrix)
myNpMtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
type(myNpMtrx)

numpy.ndarray

In [8]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
myNpMtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
np.zeros((5,8),int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
np.linspace(0,10,17,dtype=int)

array([ 0,  0,  1,  1,  2,  3,  3,  4,  5,  5,  6,  6,  7,  8,  8,  9, 10])

In [13]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.random.rand(5,2)

array([[0.24865786, 0.25378312],
       [0.59833692, 0.23010817],
       [0.98334814, 0.38705265],
       [0.06105005, 0.69358379],
       [0.69403701, 0.02977228]])

In [15]:
np.random.randn(10)

array([ 0.01911641, -1.07681816,  0.50808173,  0.73422882,  0.16196332,
        0.96991275,  0.95666376,  1.28615231,  0.09913731,  2.61882466])

In [16]:
np.random.randint(0,101,size=10)

array([65, 72, 35, 35, 74,  7, 87, 24, 59, 51])

In [17]:
np.random.rand(4)
np.random.seed(45)


In [18]:
arr = np.arange(1,25)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [39]:
myarr = np.random.randint(2,12,size=4)

array([ 6, 11, 10,  2])

In [22]:
myarr

array([5, 2, 7, 5])

In [23]:
print(myarr)

[5 2 7 5]


In [41]:
myarr.argmax()

1

In [40]:
myarr.shape

(4,)

In [26]:
myarr.reshape(4,1)

array([[5],
       [2],
       [7],
       [5]])

In [27]:
myarr

array([5, 2, 7, 5])

In [28]:
myarr=myarr.reshape(4,1)

In [29]:
myarr

array([[5],
       [2],
       [7],
       [5]])

In [30]:
myarr.shape # returns current shape of the array

(4, 1)

5