In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr= arr+5

In [7]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
4/0

ZeroDivisionError: division by zero

In [9]:
arr/

SyntaxError: invalid syntax (1728386833.py, line 1)

In [10]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
arr/0

C:\Users\piyus\AppData\Local\Temp\ipykernel_7116\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [15]:
arr= np.arange(0,10)

In [16]:
arr/0

C:\Users\piyus\AppData\Local\Temp\ipykernel_7116\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
C:\Users\piyus\AppData\Local\Temp\ipykernel_7116\4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
1/arr

C:\Users\piyus\AppData\Local\Temp\ipykernel_7116\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [23]:
np.log(arr)

C:\Users\piyus\AppData\Local\Temp\ipykernel_7116\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [31]:
arr2d = np.arange().reshape(4,5)

In [32]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
arr2d.sum(axis=0) # vertical Sum of Rows (0+5+10+15+20)

array([34, 38, 42, 46, 50])

In [38]:
arr2d.sum(axis=1) # Horizontal Sum of Columns(0+1+2+3+4)

array([15, 40, 65, 90])